### ISSUE TITLE
Integration "inactive"

### ISSUE THREAD

**Issue by gbuico** [Cyr-ius/hass-heatzy#12]
I just installed hass-heatzy using HACS. After restart my "Heatzy Pilote" is not found and th integration never asks me to provide username and password.
The integration is showing as installed in HACS and the custom-component/heatzy has been created but I don't see the integration in Configuration/Integration
I also tried to add the login information to configuration.html, restart... but i get the same result.
Heatzy Pilot is visible from the Smarthphone app.
Never had problems before with device discovery
Can you please help? Everything seems so easy that I don't know what to try more than this

**Comment by gbuico** [comment]
Update.
After several install/uninstall I managed to receive the setup menu and provide my userid and password.
The integration is now installed and visible in Configuration/Integration but it has no device.
I have only 1 entity in my installation and it's an Acova Heatzy Pilot 2 that I can regularly see in the Cozytouch appa of the smartphone.
Is it a supported device? If yes, what can I do to further debug?

**Comment by MatheGeek** [comment]
Similar situation here.    I "reactivate"  my Heatzy Pilote device as cold is arriving in Canada (it was off since June 2021)  and  it was not responding.  So  I've tried to delete and reinstall in Home Assistant and  it tooks  4 times before  I can  see  Heatzy in the Configuration/Integration menu.   
Additionally the Heatzy device was not responding on my phone either,  so  I tried to delete  and re-install my Heatzy Pilote device in the Heatzy App on my phone.   For some mysterious reasons  I never succeed to do the setup on my OnePlus 9 phone.   But  on my old  Ipad Mini 2,   it works the first time. 
So for 2 days now,  my Heatzy Pilote is back in Home Assistant,  but it was a painfull random try and error process.
